name: dago_application
description: "An application to manage incidents at a construction site"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  http: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter_login: ^5.0.0
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.2.3
  intl: ^0.17.0
  url_launcher: ^6.3.0
  image_picker: ^1.0.8
  image: ^4.2.0
  path_provider: ^2.1.3
  path: ^1.8.3
  pdf: ^3.11.0
  printing: ^5.12.0
  share_plus: ^7.2.2
  permission_handler: ^11.3.1
  flutter_archive: ^6.0.3
  open_file: ^3.3.2
  table_calendar: ^3.0.8
  dio: ^5.1.2
  another_flushbar: ^1.12.30
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/engineering.png
  fonts: 
    - family: KronaOne
      fonts:
        - asset: fonts\KronaOne-Regular.ttf
          
